name: pocketbase_chat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ">=2.12.0 <4.0.0"

dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  easy_localization: ^3.0.2
  chatview: ^1.3.1
  cupertino_icons: ^1.0.2
  # flutter_chat_ui: ^1.6.6
  flutter_login: ^4.2.1
  path_provider: ^2.0.14
  pocketbase: ^0.17.0
  image_picker: ^1.0.4
  mime_type: ^1.0.0
  image: ^4.0.17
  # intl: ^0.18.0
  get: ^4.6.5
  get_storage: ^2.1.1
  file_picker: ^6.1.1
  #open_file: ^3.2.1
  open_filex: ^4.3.2
  path: ^1.8.3
  vm_service: ^14.0.0
  # uuid: ^3.0.7

dev_dependencies: 
  flutter_lints: ^3.0.1
  # flutter_launcher_icons: ^0.13.1
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  web:
    generate: true
    image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
  macos:
    generate: true
    image_path: "assets/icon.png"

get_cli: 
  sub_folder: false

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/